apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: airflow-core-fernet-key
  namespace: airflow
spec:
  backendType: ibmcloudSecretsManager
  keyByName: true
  data:
    - key: PROD_AIRFLOW__CORE__FERNET_KEY
      property: payload
      name: AIRFLOW__CORE__FERNET_KEY
      secretType: arbitrary
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: airflow-core-sql-alchemy-conn
  namespace: airflow
spec:
  backendType: ibmcloudSecretsManager
  keyByName: true
  data:
    - key: PROD_AIRFLOW__CORE__SQL_ALCHEMY_CONN
      property: payload
      name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
      secretType: arbitrary 
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: git-access-token
  namespace: airflow
spec:
  backendType: ibmcloudSecretsManager
  keyByName: true
  data:
    - key: PROD_GIT_ACCESS_TOKEN
      property: payload
      name: GIT_ACCESS_TOKEN
      secretType: arbitrary
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: ldap-bind-password
  namespace: airflow
spec:
  backendType: ibmcloudSecretsManager
  keyByName: true
  data:
    - key: PROD_LDAP_BIND_PASSWORD
      property: payload
      name: LDAP_BIND_PASSWORD
      secretType: arbitrary
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: airflow-db-password
  namespace: airflow
spec:
  backendType: ibmcloudSecretsManager
  keyByName: true
  data:
    - key: PROD_POSTGRES_PWD
      property: payload
      name: AIRFLOW_DB_PASSWORD
      secretType: arbitrary 
      
